name: Publish NuGet Package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-github-packages:
    name: Publish To GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.*

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build src/RedcapApi/RedcapApi.csproj -c Release --no-restore

      - name: Pack
        run: dotnet pack src/RedcapApi/RedcapApi.csproj -c Release --no-build -o ./artifacts

      - name: Publish To GitHub Packages
        run: dotnet nuget push ./artifacts/*.nupkg --source https://nuget.pkg.github.com/cctrbic/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
